import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0b0f0d" },
  mapWrap: { flex: 1, position: "relative" },
  topRightBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#1b241f",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    zIndex: 2,
  },
  topRightBtnText: { color: "#fff", fontWeight: "700", letterSpacing: 0.5 },

  coordPanel: {
    position: "absolute",
    top: 50,
    right: 10,
    left: 10,
    backgroundColor: "#0f1512",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#1f2a25",
    zIndex: 2,
  },
  coordTitle: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    marginBottom: 4,
  },
  coordHint: { color: "#9fb1a7", fontSize: 12, marginBottom: 8 },
  coordRow: { flexDirection: "row", alignItems: "flex-start" },
  label: { color: "#cfd8d4", fontSize: 12, marginBottom: 4 },
  coordInput: {
    backgroundColor: "#121a16",
    borderWidth: 1,
    borderColor: "#223127",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
    color: "#e8f1ec",
  },
  coordGo: {
    backgroundColor: "#ff7a00",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
  },
  coordGoText: { color: "#fff", fontWeight: "700" },
  coordCancel: {
    backgroundColor: "#25302a",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
  },
  coordCancelText: { color: "#e8f1ec", fontWeight: "700" },

  map: { flex: 1 },
  bigBtn: {
    position: "absolute",
    bottom: 24,
    alignSelf: "center",
    backgroundColor: "#ff7a00",
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 999,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  bigBtnText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 1.2,
  },
  status: {
    position: "absolute",
    top: 10,
    left: 10,
    backgroundColor: "#00000080",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  statusText: { color: "#fff", fontSize: 12 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCard: {
    width: "90%",
    backgroundColor: "#0f1512",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#1f2a25",
  },
  modalTitle: { color: "#fff", fontSize: 18, fontWeight: "800" },
  modalSub: { color: "#9fb1a7", marginTop: 4 },
  modalCoords: {
    color: "#cfd8d4",
    fontSize: 12,
    marginTop: 8,
    marginBottom: 8,
  },

  modalScroll: {
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  noteInput: {
    backgroundColor: "#121a16",
    borderWidth: 1,
    borderColor: "#223127",
    borderRadius: 8,
    minHeight: 100,
    paddingHorizontal: 10,
    paddingVertical: 10,
    color: "#e8f1ec",
  },

  saveBtn: {
    backgroundColor: "#ff7a00",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
  },
  saveBtnText: { color: "#fff", fontWeight: "800" },
  cancelBtn: {
    backgroundColor: "#25302a",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
  },
  cancelBtnText: { color: "#e8f1ec", fontWeight: "800" },
  deleteBtn: {
    backgroundColor: "#7a1f1f",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
  },
  deleteBtnText: { color: "#fff", fontWeight: "800" },
  recBtn: {
    backgroundColor: "#b90e0a",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ff3b30",
  },
  recBtnSecondary: {
    backgroundColor: "#1b241f",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1f2a25",
  },
  stopBtn: {
    backgroundColor: "#333333",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#555",
  },
  recBtnText: { color: "#fff", fontWeight: "800", fontSize: 12 },
  recChip: {
    alignSelf: "flex-end",
    backgroundColor: "#0d1411",
    borderColor: "#1f2a25",
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  recChipText: { color: "#e8f1ec", fontWeight: "700", fontSize: 12 },
});
